[package]
name = "rdylib"
version = "0.1.0"
edition = "2021"

[lib]
name         = "rdylib"
crate-type   = ["lib", "staticlib"]

[profile.release]
strip = true
lto = true
#panic = "abort"

[dependencies]
glib = "0.17.2"